export const OPEN_MAIN_STEPS_BLOCK = 'OPEN_MAIN_STEPS_BLOCK';

export const SET_ACTIVE_PROPERTY = 'SET_ACTIVE_PROPERTY';
export const SET_ADDITIONAL_ADDRESS = 'SET_ADDITIONAL_ADDRESS';

export const SET_PROPERTY_DETAILS = 'SET_PROPERTY_DETAILS';

export const NEXT_STEP_REQUEST = 'NEXT_STEP_REQUEST';
export const PREV_STEP_REQUEST = 'PREV_STEP_REQUEST';