export const OPEN_MAIN_STEPS_BLOCK = 'OPEN_MAIN_STEPS_BLOCK';

export const SET_ACTIVE_PROPERTY = 'SET_ACTIVE_PROPERTY';
export const SET_ADDITIONAL_ADDRESS = 'SET_ADDITIONAL_ADDRESS';

export const SET_PROPERTY_DETAILS = 'SET_PROPERTY_DETAILS';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_DETAILS = 'SET_DETAILS';
export const SET_UTILITIES_DATA = 'SET_UTILITIES_DATA';
export const CREATE_PERSONAL_ACCOUNT = 'CREATE_PERSONAL_ACCOUNT';

export const NEXT_STEP_REQUEST = 'NEXT_STEP_REQUEST';
export const PREV_STEP_REQUEST = 'PREV_STEP_REQUEST';

export const SEND_STEPS_DATA_REQUEST = 'SEND_STEPS_DATA_REQUEST';
export const SEND_STEPS_DATA_SUCCESS = 'SEND_STEPS_DATA_SUCCESS';
export const SEND_STEPS_DATA_ERROR = 'SEND_STEPS_DATA_ERROR';

export const CREATE_PROPERTY_REQUEST = 'CREATE_PROPERTY_REQUEST';
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS';
export const CREATE_PROPERTY_ERROR = 'CREATE_PROPERTY_ERROR';

export const GET_USER_PROPERTY_REQUEST = 'GET_USER_PROPERTY_REQUEST';
export const GET_USER_PROPERTY_SUCCESS = 'GET_USER_PROPERTY_SUCCESS';
export const GET_USER_PROPERTY_ERROR = 'GET_USER_PROPERTY_ERROR';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const SHOW_MODAL_CONTACT_AGENT = 'SHOW_MODAL_CONTACT_AGENT';
export const CLOSE_MODAL_CONTACT_AGENT = 'CLOSE_MODAL_CONTACT_AGENT';

export const CONTACT_AGENCY_REQUEST = 'CONTACT_AGENCY_REQUEST';
export const CONTACT_AGENCY_SUCCESS = 'CONTACT_AGENCY';
export const CONTACT_AGENCY_ERROR = 'CONTACT_AGENCY_ERROR';